apiVersion: v1
kind: Service
metadata:
  name: healthchecker
  labels:
    app: healthchecker
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - port: {{ .Values.healthchecker.service.grpc.externalPort }}
    name: grpc
    protocol: TCP
    targetPort: {{ .Values.healthchecker.service.grpc.internalPort }}
  selector:
    app: healthchecker
  type: ClusterIP